### ISSUE TITLE
Allow using channels instead of just handlers in .On method

### ISSUE THREAD

**Issue by andersfylling** [andersfylling/disgord#131]
Someone on the Gopher server noted they would prefer to inject a channel to using the already defined once. This feels both more intuitive and simpler. It even reduces internal load as there is no need to empty filled up channels to avoid blocking.

DisGord should assume the channel is not blocked, and closed properly when no longer in use. It might be benefitial to add built in channel checking to the main Ctrl struct, for ease.

What needs to be decided is the channel type. `interface{}` takes everything. But perhaps a custom interface would be better.

When implemented this removes the current way channels are used.

**Comment by diamondburned** [comment]
I think an `interface{}` is fine, so long as there's a readily available type assertion function for me to copy paste :)

**Comment by andersfylling** [comment]
I should also be completely able to allow specific types:
```
newMsgChan := make(chan *disgord.MessageCreate)
client.On("MESSAGE_CREATE", newMsgChan)
```

That should be very doable.

**Comment by andersfylling** [comment]
implemented in https://github.com/andersfylling/disgord/pull/147
