### ISSUE TITLE
Quick question on unoform logging 

### ISSUE THREAD

**Issue by MostHated** [andersfylling/disgord#139]
Hey again,
   I was wondering if there was a quick and simple way to go about making the logs I manually create match the auto generated system debug/info logs? Example is, if I were to just manually type:

```Go
log.Fatal(err)
```
That imports the standard library logging. If I use:

```Go
logrus.Info("Info!")
```
Then that, of course, uses standard logrus config. Is there a way I can utilize disgords default logging instance and format? Can I do something like:

```Go
log := disgord.logging.format
log.Info("This entry is now matching to the disgord standard logging!")
```

Is there a way that exists in which I could do something like this without having to create a new logging instance and formatter?

Thanks,
-MH

**Comment by andersfylling** [comment]
The session interface gives you access to the logger. And you can inject you own instances.

example 1
```go
func handleNewMessage(s disgord.Session, evt *disgord.MessageCreate) {
	s.Logger().Info(evt.Message.Author.Username, "wrote a message")
}
```

example 2
```go
func main() {
	myLogger := logrus.New()
	client := disgord.New(&disgord.Config{
		Logger: myLogger,
	})

	myLogger.Info("log something")
}
```

example 3
```go
type CustomLogger struct {
	// you can also write your own logger type
}

// But! it must implement the disgord.Logger interface
// by adding the required methods.
var _ disgord.Logger = (*CustomLogger)(nil)

func main() {
	myLogger := CustomLogger{}
	client := disgord.New(&disgord.Config{
		Logger: myLogger,
	})

	myLogger.Info("log something")
}
```

**Comment by MostHated** [comment]
Perfect, that works for me. Much appreciated. :+1:
