### ISSUE TITLE
Query for channel / role ID's?

### ISSUE THREAD

**Issue by MostHated** [andersfylling/disgord#140]
Me again, :D 
I was wondering if it's possible to query for the actual channel and role ID's? I know I can get the names, but can the ID's be pulled as well? With my old bot the user had to enable dev mode and locate all of their current channel and role ID's and put them in the config. My ultimate goal with my new bot is to try and help make setup of my system a good bit easier by getting the current roles and channels for them and saving it.

Thanks,
-MH

**Comment by andersfylling** [comment]
The name of roles, and their ID should be in the same struct.

just change `role.Name` to `role.ID`?

I don't quite understand what you are asking tho.

`current roles and channels for them` who do you refer to as them? Are you trying to save all the guild info to file, including your bots assigned roles in those guilds?

You should be aware these can change, so it might be more ideal to query such data on start up and keep it in memory?

**Comment by MostHated** [comment]
Ah, ok. I probably didn't notice it because I was using dgrouter/exrouters's disgordrouter to get the list of groups currently, and this function just returns the list by name. 

```Go
type ListRoles struct {
	di    di.Container
	guild disgord.Snowflake
}

func (l ListRoles) Handle(ctx *disgordrouter.Context) {
	guildRoles, _ := ctx.Ses.GetGuildRoles(l.guild)
	log.Infof("Roles: %s \n", guildRoles)

	roleTable := l.renderMarkDownTable(guildRoles)
	_, err := ctx.Reply(roleTable)
	if err != nil {
		log.Print("Something went wrong when handling listroles request", err)
	}
}
```

I'll probably see about adding a getguildroleid along with it and all should be well. 

By "them" I was meaning the person using my bot. My bot is designed to allow Unity game engine asset developers to have their users verify their own purchases of said asset via Unitys web store API and then automatically gain access to locked channels for support and updates and such as doing it manually for everyone who comes in the channel can become quite a hassle. 

With my old bot each asset dev that uses it has to go in and set up which of their channels are locked and what asset they are associated with so that the users get access to the right channels as some devs have multiple, up to dozens of assets and channels.  

The role/channel ID's have always been the same in the 6 months or so I had been working with it, so I didn't know the ID could change. That is definitely good to know, as I was having the ID's reside in a config file originally. I will just have to adjust how I go about things now that I know that.

I really like the framework, so hopefully once I get a bit better with Go, I can help contribute to it's functionality. : D

Thanks again!
-MH

**Comment by andersfylling** [comment]
I see that this regards disgordrouter, which is a stand alone project from disgord. So I would redirect issues/feature request to the disgordrouter project. If you feel unsure whether to ask in the disgordrouter project or here, you're always welcome to ask here and we can figure it out together.

Also the ID won't change. I should have stated I referred to the permission bits/roles assigned to your bot.

Regarding the code you show, I assume disgordrouter uses a disgord.Session, meaning you do still use the disgord objects and methods. So I assume guildRoles are a `[]*disgord.Role` slice.

Was your issue resolved?

### Tip
if you want to sort the roles by name or id, you can use the disgord flags:
```go
guildRoles, err := ctx.Sess.GetGuildRoles(l.guild, disgord.SortByName)
if err != nil {
	ctx.Sess.Logger().Err(err)
	return 
}
```

**Comment by MostHated** [comment]
The original question was for disgord, which you answered straight away with disgord.guild having .name and .id. I just had not realized the option of doing so was there because the particular disgordrouter function was pulling the name directly so there was no option for ID in that bit of code. Now that I know that though, I can make the necessary changes to get it through the router.

As for the rest, definitely nice to know that I can easily sort like that, it will definitely come in handy.
Everything is good though now, thanks,
-MH
