### ISSUE TITLE
Handlers do not use event from middlewares

### ISSUE THREAD

**Issue by nikkelma** [andersfylling/disgord#143]
**Describe the bug**
Event handlers do not use the mutated event generated by middlewares.

**Expected behavior**
Event handlers use the mutated event generated by middlewares.

**Error messages**
No error messages. Reproducible by using the bot generation script and running the resulting bot. The `!ping` command will not produce a response, as the `replyPingToPong` function checks for `ping` (assuming a mutated event) instead of `!ping` (assuming the original event).

**Desktop:**
 - Golang version: go1.12.5 linux/amd64
 - Using Go modules? Yes

**Additional context**
The dispatcher uses the middleware to create a `localEvent` but that event is never used.
https://github.com/andersfylling/disgord/blob/f3fae703eaf43a057f803d39c42dffc982eb1224/reactor.go#L157-L165

**Comment by andersfylling** [comment]
I'll open up a PR for you and get this merged asap.
