### ISSUE TITLE
[Docs] Clarify self-bot support

### ISSUE THREAD

**Issue by nikkelma** [andersfylling/disgord#150]
Found this article regarding self bots: https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-

The summary:
> Automating normal user accounts (generally called "self-bots") outside of the OAuth2/bot API is forbidden, and can result in an account termination if found.

Could be a good idea to edit the FAQ to reflect this possibility, not required but could help give people more context.

**Comment by andersfylling** [comment]
You can't use disgord to make a self bot tho. And this will probably never be supported.
