### ISSUE TITLE
Clarify if a message event is from a guild or a direct message

### ISSUE THREAD

**Issue by andersfylling** [andersfylling/disgord#153]
## Option 1
Introduce custom event types:
 - GuildMessageCreate (GuildMessageUpdate, etc.)
 - DMMessageCreate (DMMessageUpdate, etc.)

While MessageCreate handles both origins.

## Option 2
Add a method: `Message.DirectMessage() bool`

**Comment by nikkelma** [comment]
I personally look at official discord API docs assuming that disgord implementation follows very similar patterns for clarity and reducing the learning curve. I would much more appreciate Option 2 along with a standard filter implementation for filtering MessageCreates by DM status.

**Comment by andersfylling** [comment]
Yes. Thanks for your input. I'll be using option 2. Adding  DM filter was a cool idea.
