### ISSUE TITLE
Unknown import path "zeromod"

### ISSUE THREAD

**Issue by zerinho6** [andersfylling/disgord#156]
**Describe the bug**

Hi, I just started learning Go and found about disgord, I'm already a bot dev but with JavaScript, and I really want to test the things that I learn with discord and Go, but I'm having problem after executing ``go test`` and go not being able to find a certain package, "zeromod" 

**Error messages**
```
C:\Users\zerinho\Desktop\BetterLearnGo\zeroBot>go test
go: finding github.com/andersfylling/disgord v0.11.3
go: finding github.com/andersfylling/snowflake/v3 v3.0.2
go: finding github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: finding github.com/stretchr/testify v1.3.0
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/modern-go/reflect2 v1.0.1
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/gorilla/websocket v1.4.0
go: finding go.uber.org/zap v1.9.1
go: finding golang.org/x/net v0.0.0-20190213061140-3a22650c66bd
go: finding golang.org/x/crypto v0.0.0-20190219172222-a4c6cb3142f2
go: finding go.uber.org/atomic v1.3.2
go: finding github.com/json-iterator/go v1.1.5
go: finding github.com/sergi/go-diff v1.0.0
go: finding go.uber.org/multierr v1.1.0
go: finding github.com/davecgh/go-spew v1.1.0
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding github.com/stretchr/objx v0.1.0
can't load package: package zeromod: unknown import path "zeromod": cannot find module providing package zeromod
```

go.mod:

```
module zeromod

go 1.12

require github.com/andersfylling/disgord v0.11.3
```
**Desktop (please complete the following information):**
 - Golang version: v1.12.4
 - Using Go modules? yes

**Additional context**

(os: Windows 10)

I'm only starting with modules so I'm not sure if I'm doing something wrong, please tell me if I'm.

**Comment by victionn** [comment]
what does this have to do with disgord

**Comment by zerinho6** [comment]
It doesn't? Sorry then. I'll wait for andersfylling reply to confirm and close the issue.

**Comment by andersfylling** [comment]
This is not disgord related. I would advice reading up on the holang github or perhaps asking in the golang discord, as the issue isnt immidiatly apparent to me.

Btw, zeromod is your package.
