### ISSUE TITLE
"not by bot" filter for reactions

### ISSUE THREAD

**Issue by Wobbley** [andersfylling/disgord#157]
Going to pre-face this by saying I am both new to GO and the Discord API.

I created an event listener for ``EvtMessageReactionAdd``, but quickly realized this has no filters, such as ignoring reactions made by the bot. Currently I just solved it by storing my bot ID and doing nothing if the given User ID for the reaction is the same as the bot. Would it make sense to create a reaction filter for this? 

I don't mind trying to fork and giving a PR on this. If you believe there is value to it, and has a good reward vs effort ratio.

**Comment by andersfylling** [comment]
Yeah, I think that could be nice. Hopefully you can base the logic on what already exists, such that you dont have to start from scratch. But if you want to play around and solve it on your own way, that is also okay.

**Comment by andersfylling** [comment]
Hi, did you want to write a PR for this? I'm doing a issue hunt, so just curious.

**Comment by Wobbley** [comment]
I found a way around it :see_no_evil: You can just nuke this issue if you want

**Comment by andersfylling** [comment]
oh, was it not worth a new function?

**Comment by Wobbley** [comment]
I just did a quick if check like mentioned earlier, since the bot was quite small and simple.
