### ISSUE TITLE
Enhanced ready event for guild loading.

### ISSUE THREAD

**Issue by victionn** [andersfylling/disgord#198]
**Is your feature request related to a problem? Please describe.**
Guilds are not loaded for a few seconds after the ready event fires

**Describe the solution you'd like**
To make an enhanced ready event which makes use of the properties in https://discordapp.com/developers/docs/topics/gateway#ready-ready-event-fields to determine how many guilds the client is expecting to collect, and then emit the new ready event _after_ they are all loaded. This allows for things like reporting statistics away to different services at boot time.

**Comment by andersfylling** [comment]
How about we add a bool to the .Ready?
```go
client.Ready(func(){}, true)
```

```go
func (c *Client) Ready(cb func(), waitForGuilds bool) {...}
```

**Comment by andersfylling** [comment]
How about we add a method: GuildsReady(cb func())
