### ISSUE TITLE
disgord does not complain about unknown handler signatures

### ISSUE THREAD

**Issue by EpsilonPrime** [andersfylling/disgord#208]
If you set up a listener with:
client.On(disgord.EvtMessageCreate, func(session *disgord.Session, evt *disgord.MessageCreate) {

instead of:

client.On(disgord.EvtMessageCreate, func(session disgord.Session, evt *disgord.MessageCreate) {

the code will still compile but the routine will never get called.

**Comment by andersfylling** [comment]
Generate switch check for range of valid inputs. Also, a lot of beginners are confused about interfaces. Detecting *disgord.Session and give a custom error message to help them out.
