### ISSUE TITLE
UpdateStatus while not connected will silently do nothing

### ISSUE THREAD

**Issue by EpsilonPrime** [andersfylling/disgord#209]
If you call client.UpdateStatus before you Connect nothing will happen.

It'd be nice to get an error in this case.  There's probably a subtle difference between trying to connect and actually being connected.  It can happen to fail if you aren't connected at the time (temporary connection failure which sometimes happens to me during startup).  But if I never called Connect it could be a hard failure (fatal) so I can fix my code.

**Comment by andersfylling** [comment]
Fix is to override function pointer of private emit in ShardManager to point to a queue (A) before shards are initialized, then point to normal shards again and populate shard queues with the contents from queue A.
