### ISSUE TITLE
Add a convenience method for reactions

### ISSUE THREAD

**Issue by EpsilonPrime** [andersfylling/disgord#211]
Currently the disgordrouter.Context provides a convenience method for replying to a message which is extremely handy.  Could we add additional convenience methods for reactions?

For instance to react to something you need to write:

` ctx.Ses.CreateReaction(ctx.Msg.ChannelID, ctx.Msg.ID, "X")
`

But with a convenience function it would just be:

`ctx.React("X")
`

One related task would be removing reactions.  Perhaps ctx.Unreact("X") could make that easier.

The specific use case I see reactions used is for bots showing progress for long running commands.  They tend to put a reaction that says they are working on a problem and then replace (remove/add) an icon to show the state of the command (success/failure).

**Comment by andersfylling** [comment]
Disgordrouter isn't a part of disgord. It's an independent wrapper. While disgord provides the Message.Reply, a Message.React and Message.Unreact can definetly be added.
