### ISSUE TITLE
Better support for distributed instances

### ISSUE THREAD

**Issue by andersfylling** [andersfylling/disgord#224]
To properly scale each instance needs to share the following data:
- REST rate limit buckets
- websocket identify rate limits

My current idea is to just allow a simple GetSet interface in the config. The devs can then use whatever they want to deal with this. 
 - GetSet puts a write lock on the data, fetches it, and updates it and unlocks it again

**Comment by paulhobbel** [comment]
Seems like a good idea, as that would also allow the use of things like redis. Question though, how would you make it typesafe?

**Comment by andersfylling** [comment]
Current interface:
```go
type BucketTransactioner interface {
	GetSet(atomicTransaction func(bucket string) (updated string))
}
```

I think it's fairly understandable just by the naming here. The internal DisGord logic needs to do a write locked change to the data. DisGord then handles unmarshalling and marshalling as I see zero reason an outside should change the data.

**Comment by andersfylling** [comment]
I changed the interface. And I think the following is sufficient:
```go
type BucketTransactioner interface {
	GetSet(bucketID string, atomicTransaction func(bucketData []byte) (updated []byte, err error))
}
```

**Comment by andersfylling** [comment]
And I changed it again. I'm going to let the behaviour for distributed instances be that only one request can be sent at a time. This is because I'm prioritizing single instance systems so I'm actually able to get to v1.

New version:
```go
type BucketTransactioner interface {
	GetSet(bucketID string, atomicTransaction func(bucketData []byte, globalBucketData []byte) (updated []byte, updatedGlobal []byte, err error))
}
```

This can obviusly be improved from a community contribution, where you can selectively require the global bucket. But for now, distributed instances is supported just not very efficient.

**Comment by andersfylling** [comment]
All previous interfaces/ideas are discarded. After several iterations and brain storming, I've decided that distributed systems must create their own rate limiting system as there are a lot of moving parts and might differ depending on their setup (I'm not sure how I can make a integration into the internal system that is flexible enough, so this seems like the better aproach).

Here are the final REST interfaces that a user can implement:
```go
// RESTBucket is a REST bucket for one endpoint or several endpoints. This includes the global bucket.
type RESTBucket interface {
	// Transaction allows a selective atomic transaction. For distributed systems, the buckets can be
	// eventual consistent until a rate limit is hit then they must be strongly consistent. The global bucket
	// must always be strongly consistent. Tip: it might be easier/best to keep everything strongly consistent,
	// and only care about eventual consistency to get better performance as a "bug"/"accident".
	Transaction(context.Context, func() (*http.Response, []byte, error)) (*http.Response, []byte, error)
}

// RESTBucketManager manages the buckets and the global bucket.
type RESTBucketManager interface {
	// Bucket returns the bucket for a given local hash. Note that a local hash simply means
	// a hashed endpoint. This is because Discord does not specify bucket hashed ahead of time.
	// Note you should map localHashes to Discord bucket hashes once that insight have been gained.
	// Discord Bucket hashes are found in the response header, field name `X-RateLimit-Bucket`.
	Bucket(localHash string, cb func(bucket RESTBucket))

	// BucketGrouping shows which hashed endpoints falls under which bucket hash
	// here a bucket hash is defined by discord, otherwise the bucket hash
	// is the same as the hashed endpoint.
	//
	// Hashed endpoints are generated by the Request struct.
	BucketGrouping() map[string]string
}
```
