### ISSUE TITLE
Client.CreateBotURL panics in powershell

### ISSUE THREAD

**Issue by andersfylling** [andersfylling/disgord#233]
See issue: https://github.com/jfoster/discord-slowmode-bot/issues/5

**Comment by andersfylling** [comment]
fixed in commit eba83ed

Simply deprecates CreateBotURL() and introduces InviteURL()

**Comment by jfoster** [comment]
Possibly relates to this? https://github.com/golang/go/issues/21881

**Comment by andersfylling** [comment]
I didn't even google but that seems to be the answer since it works on Linux (the superior platform :p).
