### ISSUE TITLE
Discussion about X-Audit-Log-Reason header field

### ISSUE THREAD

**Issue by andersfylling** [andersfylling/disgord#235]
Discord [states here that](https://discordapp.com/developers/docs/resources/audit-log#audit-logs):
```
Whenever an admin action is performed on the API, an entry is added to the respective guild's audit log. You can 
specify the reason by attaching the X-Audit-Log-Reason request header. This header supports url encoded utf8 
characters.
```

This is currently not supported in DisGord. That being said, I'm not sure what an admin action is; only actions that requires the permission ADMINISTRATOR?

**Comment by GreemDev** [comment]
Basically anything that modifies the guild. I believe Channel creation/deletion, as well as modification, is included...but it seems that Message Delete logging is inconsistent at best

**Comment by andersfylling** [comment]
I guess I can just add a Reason field to all related Params structs. Ty
