### ISSUE TITLE
Client.GetGuild() returns an empty Channels Parameter

### ISSUE THREAD

**Issue by Togtja** [andersfylling/disgord#240]
**Describe the bug**
When calling 
```
//Error check are done on both, but omitted here
Client.CreateGuildChannel(serverid, "test1", nil, disgord.IgnoreEmptyParams)
Client.CreateGuildChannel(serverid, "test2", nil, disgord.IgnoreEmptyParams)

server := Client.GetGuild(serverid, disgord.IgnoreEmptyParams)
if len(server.Channles) > 0 {
     fmt.Println("This is expected behavior")
}
```

**Desktop:**
 - Golang version:  v1.13.4
 - Using Go modules? yes

**Additional**
server does return the name correctly, so the issue is not that server is empty

**Comment by andersfylling** [comment]
Are you using DisGord without connecting to the gateway? Cause the Discord API only populates the channels fields of a Guild in GUILD_CREATE events.

**Comment by Togtja** [comment]
Then there have been a misunderstanding on my part. I don't think I am connecting to a gateway, unless DisGord does this for me in disgord.New
If it is not to much of a bother, how do you setup a gateway in DisGord?

**Comment by andersfylling** [comment]
Usually by calling Client.Connect(). You can see this in most of the examples.
