### ISSUE TITLE
Pass *disgord.Embed directly into (*Client).SendMsg

### ISSUE THREAD

**Issue by coadler** [andersfylling/disgord#243]
**Is your feature request related to a problem? Please describe.**
I'm a little lazy and having to wrap the embed object in a `*disgord.CreateMessageParams` to send an embed message starts to cause lots of unnecessary indentation once you finally make it down to the `[]*disgord.EmbedField` slice. 

**Describe the solution you'd like**
The ability to pass a `*disgord.Embed` directly into `(*Client).SendMsg` for extra laziness.

**Comment by andersfylling** [comment]
fixed in https://github.com/andersfylling/disgord/commit/e64c3054052802b13dcb9828140e4cb761f02484
