### ISSUE TITLE
User struct returning as nil on GuildMemberAdd

### ISSUE THREAD

**Issue by puckzxz** [andersfylling/disgord#248]
**Describe the bug**
The User struct in the returned Member struct is nil

**Expected behavior**
The struct should not be nil

**Error messages**
Screenshots attached below

**Desktop (please complete the following information):**
 - Golang version: go1.13.4 windows/amd64
 - Using Go modules? yes
 - DisGord version? v0.15.1
 - Connected to the gateway before using REST methods? yes

**Additional context**
![Code_-_Insiders_vI9SaKit31](https://user-images.githubusercontent.com/10362744/69988980-afb8b800-1510-11ea-9709-ff055242e017.png)
![Code_-_Insiders_cFOBhiZVE4](https://user-images.githubusercontent.com/10362744/69989191-18a03000-1511-11ea-8d1c-65b24d979bd0.png)

**Comment by andersfylling** [comment]
please, use copy/paste of code so i can quickly run the sample. That being said, thank you for the report. I'm looking into it.

A quick fix is to call `Member.GetUser()` as this will always ensure the user object.

**Comment by andersfylling** [comment]
This is fixed in the next release

**Comment by puckzxz** [comment]
Thanks for the quick fix.  I love this module and I appreciate the work you put into it.

**Comment by Merded** [comment]
Same problem on v0.26.9. @andersfylling

**Comment by andersfylling** [comment]
Ill add a test and patch it when i wake up tomorrow! Must have happened
when the new cache rolled in

**Comment by andersfylling** [comment]
btw, I always recommend using Member.GetUser(..). The cache returning nil is a bug. But with this you'll always have an updated user struct.
