### ISSUE TITLE
(*Message).MentionChannels always nil

### ISSUE THREAD

**Issue by coadler** [andersfylling/disgord#249]
**Describe the bug**

`(*Message).MentionChannels` always seems to be nil, even if channels are mentioned in the message.

**Comment by andersfylling** [comment]
Does the tested scenarios comply with the requirements specified in the Discord docs? https://discordapp.com/developers/docs/resources/channel#message-object-message-structure

**Comment by andersfylling** [comment]
That being said, I'm completely fine with parsing the Message.Content and populate the Message.MentionChannels.

**Comment by coadler** [comment]
Oops, I did not see that limitation in the docs. My tested scenario does
not fall under the cases where it works.
