### ISSUE TITLE
use of context

### ISSUE THREAD

**Issue by andersfylling** [andersfylling/disgord#252]
Notice how the std uses context for requests: https://golang.org/pkg/net/http/#NewRequestWithContext

While here it is forced. Is it worth creating wrappers for all REST methods, one set with "WithContext" suffix and another without?

Edit: how can it be properly used in the connect method. This essentially just triggers a reconnect, as a connect may fail. Should context be removed from such a method? It can't be used to set the timeout for individual connects anyways.

**Comment by coadler** [comment]
It's worth noting the reason they have the duplicate `WithContext` functions is because the Go 1 compatibility promise says they're unable to break the API.

**Comment by nikkelma** [comment]
I appreciate requiring context, even on Connect - specifically if a `Connect`'s intermediate REST calls time out.
