### ISSUE TITLE
Voice Close Code 4014 reconnect loop

### ISSUE THREAD

**Issue by Timon23** [andersfylling/disgord#258]
**Describe the bug**
1. Bot connects to VC
2. User kicks the bot out of the VC via the right click menu
3. Bot goes into reconnect loop and fails every time

**Expected behavior**
Bot is disconnected with no errors and no retries to reconnect.

**Error messages**
{"level":"debug","ts":1580417500.3409872,"caller":"gateway/client.go:508","msg":"[[ws-v,s:11,shard:0] failed to get reader: received close: status = StatusCode(4014) and reason = \"Disconnected.\"]","lib":"DisGord","ver":"v0.16.3"}

**Desktop (please complete the following information):**
 - Golang version: v1.13.1
 - Using Go modules? yes
 - DisGord version? v0.16.3
 - Connected to the gateway before using REST methods? yes

**Additional context**
Debug error messages are spammed with a lot more than above stated.

The bot works just fine. Just the spamming of log messages.

Voice Close Event Code 4014 has a note saying that one shouldn't try to reconnect.
https://discordapp.com/developers/docs/topics/opcodes-and-status-codes#voice

**Comment by andersfylling** [comment]
With this I think the close method on voice should be rewritten to be a noop; see #259 to avoid a race.

Issue was found and it seems to be incorrectly handling the websocket errors from nhooyr. Should be out with a patch soon - I hope.
