### ISSUE TITLE
Incorrect ratelimit handling for adding reactions

### ISSUE THREAD

**Issue by Kelwing** [andersfylling/disgord#262]
**Describe the bug**
Quick successive CreateReaction calls result in some erroring out with an httd.ErrREST error containing a ratelimit error.

**Expected behavior**
The ratelimit for reactions should be handled correctly, and should retry instead of erroring out.

**Error messages**
```
*httd.ErrREST
You are being rate limited. ---- {
  "global": false, 
  "message": "You are being rate limited.", 
  "retry_after": 155
}
```

**Desktop (please complete the following information):**
 - Golang version: 1.13
 - Using Go modules? yes
 - Disgord version? v0.16.3
 - Connected to the gateway before using REST methods? yes

**Additional context**
I have CancelRequestWhenRateLimited set to false.

**Comment by andersfylling** [comment]
Does this apply to your situation?

```
Routes for controlling emojis do not follow the normal rate limit conventions. These routes are specifically limited on a per-guild basis to prevent abuse. This means that the quota returned by our APIs may be inaccurate, and you may encounter 429s.
```
https://discordapp.com/developers/docs/topics/rate-limits#rate-limits

**Comment by Kelwing** [comment]
I think that exception is specifically for emoji management, not reactions.  I do know there is a special exception to the major parameters rule for reactions, where Discord only counts the channel.id parameter and ignores the rest, so the ratelimit for the create reaction endpoint are calculated on a per-channel basis, so you might need to add that exception.

**Comment by andersfylling** [comment]
How would you add a test for this btw?
https://github.com/andersfylling/disgord/blob/ec24c19645f96c5558f6d5de9753193d39588a0e/internal/httd/request_test.go#L7

**Comment by Kelwing** [comment]
Add 10 emoji's in a row, it will fail if this isn't handled correctly.

**Comment by andersfylling** [comment]
```go
	client := disgord.New(disgord.Config{
		BotToken: token,
	})

	emoji := "348ty4QTPTQCJO_:658985066873225216"

	for i := 0; i < 15; i++ {
		err := client.CreateReaction(context.Background(), 673893562898841627, 674755797812641792, emoji)

		if err != nil {
			j := i
			fmt.Println(j, err)
		}
	}
```

can you provide your code? this does not seem to trigger it. so 10 unique emojis?

**Comment by Kelwing** [comment]
Ya, it has to be 10 unique ones, the current ratelimiter works if you just use the same emoji over and over

**Comment by Kelwing** [comment]
The specific code that I'm using is this, which only adds two emoji's, but triggers it intermittently
```go
err = client.CreateReaction(context.Background(), m.ChannelID, m.ID, "✅")
// some error checking
err = client.CreateReaction(context.Background(), m.ChannelID, m.ID, "❌")
// some more error checking (returns a non-nil error about 60% of the time in my testing)
```

**Comment by andersfylling** [comment]
So are you adding these reactions to potentially different guilds?

**Comment by Kelwing** [comment]
During my testing, it's a single message in a single channel, in a single guild.  `m` in the above example doesn't change between calls to CreateReaction.

**Comment by andersfylling** [comment]
Reproducing your situation here:
```go
	client := disgord.New(disgord.Config{
		BotToken: token,
		Logger:   log,
	})
	defer client.StayConnectedUntilInterrupted(context.Background())

	client.On(disgord.EvtMessageCreate, func(s disgord.Session, e *disgord.MessageCreate) {
		m := e.Message
		err := s.CreateReaction(context.Background(), m.ChannelID, m.ID, "✅")
		fmt.Println(err)

		err2 := s.CreateReaction(context.Background(), m.ChannelID, m.ID, "❌")
		fmt.Println(err2)
	})
```

then in a channel, I *spam* "a" like 30 times as fast as I can. I get one rate limit and that is due to a bucket update. 

You say consecutive reactions of the same type, So I assume N reactions are being sent in a loop. Wrapping the content of the message create handler in a for loop with 10 rounds, yields the same result. One rate limit, due to a network race. I'll look into that, but I am unable to replicate a hit rate of 60%.

**Comment by Kelwing** [comment]
The difference in rate of replication could come down to any number of factors, network latency to Discord, differences in hosting environment, etc.

**Comment by andersfylling** [comment]
What other REST calls are you using?

**Comment by Kelwing** [comment]
In my tests I would have only been calling CreateMessage to create the message that the reactions will be applied to, and then the two CreateReaction calls.

**Comment by Kelwing** [comment]
This repro's the issue without fail as far as I can tell:
```go
client := disgord.New(
		disgord.Config{
			BotToken: token,
		},
	)
	defer client.StayConnectedUntilInterrupted(context.Background())

	client.On(disgord.EvtMessageCreate, func(s disgord.Session, evt *disgord.MessageCreate) {
		if evt.Message.Content != "reactiontest" {
			return
		}
		m, _ := s.CreateMessage(context.Background(), evt.Message.ChannelID, &disgord.CreateMessageParams{
			Content: "Testing",
		})

		err := s.CreateReaction(context.Background(), evt.Message.ChannelID, m.ID, "❤️")
		fmt.Println(err)
		err = s.CreateReaction(context.Background(), evt.Message.ChannelID, m.ID, "🥺")
		fmt.Println(err)
		err = s.CreateReaction(context.Background(), evt.Message.ChannelID, m.ID, "😂")
		fmt.Println(err)
		err = s.CreateReaction(context.Background(), evt.Message.ChannelID, m.ID, "🥰")
		fmt.Println(err)
		err = s.CreateReaction(context.Background(), evt.Message.ChannelID, m.ID, "🤷")
		fmt.Println(err)
	})
```
Output:
```
go run .
<nil>
You are being rate limited. ---- {
  "global": false, 
  "message": "You are being rate limited.", 
  "retry_after": 121
}

You are being rate limited. ---- {
  "global": false, 
  "message": "You are being rate limited.", 
  "retry_after": 46
}

<nil>
You are being rate limited. ---- {
  "global": false, 
  "message": "You are being rate limited.", 
  "retry_after": 128
}
```

**Comment by andersfylling** [comment]
Regardless, I discovered a bug: URLs with an emoji/unicode was not transformed correctly. I've added it as a unit test now and hopefully it will fix the issues you encounter as well!

**Comment by andersfylling** [comment]
It seems that the hashed URL for creating a reaction doesn't handle unicodes very well:

`/channels/486833611564253186/messages/540519319814275089/reactions/🥺/@me => PUT:/channels/486833611564253186/messages/{id}/reactions/🥺/@me`

The unicode/emoji here should transform into a `{emoji}`, otherwise the reactions won't be able to find the same bucket.

**Comment by andersfylling** [comment]
@Kelwing Hi, can you see if you still have issues with the latest commit?
