### ISSUE TITLE
All command names must be unique

### ISSUE THREAD

**Issue by andersfylling** [andersfylling/disgord#275]
Otherwise the program should panic due to incorrect use.

Also applies to command aliases.

**Comment by Lukaesebrot** [comment]
Shouldn't we give the developer the possibility to override commands programmatically? In some cases that may be useful.

**Comment by andersfylling** [comment]
Sure, this constraint only states you must have a unique identifier for a command.

Perhaps a guild would be interested in refactoring a command name to their preference.
