### ISSUE TITLE
Reaction ratelimits still seem a bit finicky

### ISSUE THREAD

**Issue by Kelwing** [andersfylling/disgord#282]
**Describe the bug**
The previous fix worked great for using JUST unicode emoji's, however, I'm still getting "You are being rate limited" errors if I mix and match unicode and custom emoji's and try to rapidly add them to the same message.

**Expected behavior**
The emoji's should be added successfully.

**Error messages**
```{"level":"info","ts":1586999544.8985093,"caller":"*snip*:402","msg":"You are being rate limited.\n{\n  \"global\": false, \n  \"message\": \"You are being rate limited.\", \n  \"retry_after\": 131\n}\n\nPUT:/channels/676865924971626532/messages/{id}/reactions/{emoji}:700149757036986479/@me => []"}```

**Desktop (please complete the following information):**
 - Golang version: 1.13.5
 - Using Go modules? yes
 - Disgord version? v0.16.5
 - Connected to the gateway before using REST methods? yes

**Additional context**
I'm trying to build interactive menu's using reactions, so adding emoji's in quick succession is ideal.

**Comment by andersfylling** [comment]
Could you provide a quick code for this?

Even adding the situation here: https://github.com/andersfylling/disgord/blob/develop/internal/httd/request_test.go

Could help yielding more insight and ensure future changes don't re-introduce the issue.

**Comment by Kelwing** [comment]
I figured this one out.  It was an issue on my end, but just for the sake of transparency: The issue was caused by an incorrectly formatted emoji name.  If you send an emoji and include the colons in the name, such as `:testing:` instead of just setting the name as `testing`, discord will still accept the emoji and print it, but the bucket calculations calculate the wrong bucket, hence the 429.

**Comment by andersfylling** [comment]
I feel like such a check can be added to disgord. A simple unwrap.
