### ISSUE TITLE
Omit Embed.Color when set to 0

### ISSUE THREAD

**Issue by IntrntSrfr** [andersfylling/disgord#284]
**Is your feature request related to a problem? Please describe.**
Embed color is shown as black instead of transparent when Embed.Color is set to 0. 

**Describe the solution you'd like**
Add 'omitempty' to the Embed.Color field

![image](https://user-images.githubusercontent.com/24961582/79712487-3f49e200-82cb-11ea-81ff-6d2818228f52.png)

Top image shows embed utilizing transparency, vs bottom one where color is set to black.

**Comment by andersfylling** [comment]
kinda feels bad if you want the color to be black. But I understand the issue. I gotta tinker a little on this.

**Comment by IntrntSrfr** [comment]
While that is true, remember that you can put the color to lets say #010101, and most people will just see that as black and be fine with it is what i'd think. While there are no other alternatives to get something close to the transparency.

**Comment by andersfylling** [comment]
Fair, added.

https://github.com/andersfylling/disgord/commit/2455a3cd2d9710c1884ac3083b75665a48ecf857
