### ISSUE TITLE
DELETE all reactions and PUT reaction end up in different buckets

### ISSUE THREAD

**Issue by Kelwing** [andersfylling/disgord#287]
**Describe the bug**
DELETE all reactions and PUT reaction end up in two different buckets due to the way buckets for reactions are calculated.  These calls fall under the same ratelimit.  If you were to make paginated embeds, and clear all reactions prior to adding new ones for a new page, you'd get a 429.

**Expected behavior**
DELETE all reactions and PUT reaction should end up in the same bucket.

**Error messages**
N/A

**Desktop (please complete the following information):**
 - Golang version: v1.13.7
 - Using Go modules? yes
 - Disgord version? v0.16.5
 - Connected to the gateway before using REST methods? yes

**Additional context**
I am currently preparing a PR to merge all reaction related calls into the same bucket.  I'm creating the bug report to document the problem.

**Comment by andersfylling** [comment]
is this actually not handled by the update function that gets called after a discord response?

I seem to remember I use the bucket hash created in the REST reply to link buckets together. But it's been a while, so I'm not 100% certain.

**Comment by Kelwing** [comment]
It doesn't seem to be.  During my testing, simply merging all of the endpoints for reactions together fixed the issue.

**Comment by Kelwing** [comment]
Upon further investigation, it seems you are correct.  The issue seems the only appear upon the first invocation of the command within a given channel.

**Comment by andersfylling** [comment]
The concern is that discord may alter buckets in the future or use dynamic
logic to define the buckets. So im not sure if its worth it to hardcode it

**Comment by andersfylling** [comment]
I'm closing this for now. But feel free to re-open it if you find a more flexible approach =)
