### ISSUE TITLE
Export `std.msgFilter`

### ISSUE THREAD

**Issue by gastrodon** [andersfylling/disgord#317]
**Is your feature request related to a problem? Please describe.**
Type `*std.msgFilter` is unexported (as far as I can tell, I didn't see an alias for it), which makes properly declaring types impossible. Consider the following snippet
```go
func main() {
	var client *disgord.Client = disgord.New(disgord.Config{
		BotToken: os.Getenv("DISCORD_TOKEN"),
		Logger:   logger,
	})

	var filter *std.msgFilter
	var err error
	if filter, err = std.NewMsgFilter(context.Background(), client); err != nil {
		panic(err)
	}

	defer client.StayConnectedUntilInterrupted(context.Background())
	client.On(disgord.EvtMessageCreate, handler.Handle)
}
```

Currently, this appears to be impossible to compile. I know that I may `filter, err := std.NewMsgFilter(...)`, but I find that style of go incredibly unattractive, and so that's not how I like to write my code. 

**Describe the solution you'd like**
Since `*std.msgFilter` is returned by exported things, either:
- it should be exported, or
- it should have some exported alias

**Comment by gastrodon** [comment]
If changing that type name to `std.MsgFilter` is something that you're open to, I can make a pull with that change

**Comment by andersfylling** [comment]
I don't view it as a good reason to change it. The current logic behind it is to shield devs from doing something weird with it. If you do not like how the Go language is designed (:=) and I want to work around that, then that's okay. But I don't consider it a valid reason to adjust Disgord code. 

If several people want it changed, then I'm more open to it. But there needs to be a "community vote".

Also the std, isn't a requirement, it's just some helpers to clean up your handlers.

Btw; in that example you're not using the filter.

**Comment by gastrodon** [comment]
Here is a more concrete example where a `*std.msgFilter` might be useful if exported, which is what I use to avoid cluttering `main` with the filter deceleration. This code would be _actually_ impossible without exporting it, regardless of style choice.
```go

func filtrate(client *disgord.Client) (filter *std.MsgFilter) {
	var err error
	if filter, err = std.NewMsgFilter(context.Background(), client); err != nil {
		panic(err)
	}

	filter.SetPrefix(handler.PREFIX)
	return
}

func main() {
	var client *disgord.Client = disgord.New(disgord.Config{
		BotToken: os.Getenv("DISCORD_TOKEN"),
		Logger:   logger,
	})

	defer client.StayConnectedUntilInterrupted(context.Background())

	var filter *std.MsgFilter = filtrate(client)
	client.On(
		disgord.EvtMessageCreate,
		filter.HasPrefix,
		std.CopyMsgEvt,
		filter.StripPrefix,
		handler.Handle,
	)
}
```
Even if the type should not be changed, it might be worth introducing an alias to it somewhere just so that it can be exported

**Comment by gastrodon** [comment]
> But there needs to be a "community vote"
Where would such a vote take place? The linked discord api discord server?

**Comment by andersfylling** [comment]
It could be voted on in this issue. But it seems fairly unlikely. If you for some reason want to return the filter after you've already used it. You can create a interface for the methods you require. If there is no need for the struct content to be accessed, then there is no reason to export the struct.
