### ISSUE TITLE
Pointer to documentation on changing nicknames?

### ISSUE THREAD

**Issue by vessenes** [andersfylling/disgord#320]
I am new to programming a discord bot. Thanks for disgord, it's really cool!

I'd like to have the bot change its nickname depending on the functionality it's providing in a channel. I've added the bot with Administrator permissions (permissions=8), and it can talk to me on a channel on my private server.

I've also added an Admin role to my server, and granted that role to the bot.

However, when I try and execute a function to change a nickname, I get permissions error messages:

```client.UpdateGuildMember(context.Background(), msg.GuildID, msg.Author.ID).SetNick("some nickname").Execute())```

```
Missing Permissions
{"message": "Missing Permissions", "code": 50013}
PATCH:/guilds/<guildID>/members/{id} => []
```

Any guidance? I feel I must be missing something very simple, but I can't find pointers on this in godoc or elsewhere.

**Comment by adityaxdiwakar** [comment]
First off, you said you wanted for the bot to change its name, but this code changes the nickname of the person who sent the message, that's something to consider.

However, the reason for your error is that when you're sending a message in the channel, the bot attempts to change your username as you said. However, presumably you own the guild and therefore the bot cannot change it, as actions to the Owner of the server behaves differently.

Your code should work if you grab an alternate account (that does not own the server it is in) and test it that way. 

Hopefully this helped 😁

**Comment by vessenes** [comment]
Thanks! I validated this nickname change works on an alt account. 

Can a bot change its own nickname? I have hardcoded its ID into the call and get the Authorization error.

**Comment by vessenes** [comment]
Update: I'm going to close this. I'm looking at how Tupperbot injects into conversations, and will try and replicate with disgord.

**Comment by adityaxdiwakar** [comment]
Yes, bot can change its own nickname assuming it has the proper permissions.
