### ISSUE TITLE
NewMessageByString not declared by package disgord error

### ISSUE THREAD

**Issue by DutchEllie** [andersfylling/disgord#337]
**Describe the bug**
The function described in the title along with many more functions don't work after transferring my code from my Windows machine to my Ubuntu server environment. Some functions do work, but most others just don't. They're not recognized by either the go language server (I think gopls) nor by the go compiler when I run `go run .` in the main folder. 

**Expected behavior**
I expected the program to compile perfectly just like it does on my Windows machine.

**Error messages**
#competingvreughtbot
./main.go:44:13: undefined: disgord.NewMessageByString
./main.go:45:11: session.CreateMessage undefined (type disgord.Session has no field or method CreateMessage)
./main.go:54:21: session.GetGuild undefined (type disgord.Session has no field or method GetGuild)
./main.go:63:13: undefined: disgord.NewMessageByString
./main.go:64:11: session.CreateMessage undefined (type disgord.Session has no field or method CreateMessage)
./main.go:68:13: undefined: disgord.NewMessageByString
./main.go:69:11: session.CreateMessage undefined (type disgord.Session has no field or method CreateMessage)
./main.go:84:14: session.CreateMessage undefined (type disgord.Session has no field or method CreateMessage)
./main.go:84:75: undefined: disgord.NewMessageByString
./main.go:91:14: session.CreateMessage undefined (type disgord.Session has no field or method CreateMessage)
./main.go:91:14: too many errors

**Desktop (please complete the following information):**
 - Golang version on windows: v1.13.8 windows/amd64
 - Golang version on ubuntu: (first I think somewhere in version 1.12, but updated now to be) v1.15.2 linux/amd64
 - Using Go modules? not on linux, as far as I can see. On Windows vscode had a small "Go Modules is enabled for this project" at the bottom
 - Disgord version? latest
 - Connected to the gateway before using REST methods? well yes and no, it did work on windows successfully

**Additional context**
I probably need to enable modules, but I have absolutely no idea how.

**Comment by andersfylling** [comment]
It's because you stopped using go module. And now you're dealing with
breaking changes.

Just activate modules again.

**Comment by DutchEllie** [comment]
I have no clue why other code does work, but it did work now. Sadly for some reason `go run .` seems to have stopped working...

**Comment by andersfylling** [comment]
Because you were using go modules. Now youre using code that's undergone
breaking change.
