### ISSUE TITLE
Discord Slash Commands / Interactions

### ISSUE THREAD

**Issue by zackartz** [andersfylling/disgord#370]
**Is your feature request related to a problem? Please describe.**
No, Discord just released new functionality to their API and I would use it if it was in the library.

**Describe the solution you'd like**
I would like to have a easy to use interface to registering slash commands and a way to handle the "INTERACTION_CREATE" event.

**Describe alternatives you've considered - optional**
Handling these by sending a post request and doing a raw WS connection is possible but having it in the library would be nice.

**Additional context - optional**
https://discord.com/developers/docs/interactions/slash-commands

Thanks :)

**Comment by andersfylling** [comment]
Yes, I want this as well!

For anyone that wants to start messing around with this and contributing, there is a new branch: feature/slash-commands

**Comment by vinicius507** [comment]
The Slash Commands branch development was halted?

**Comment by jollyroger-jelly** [comment]
> The Slash Commands branch development was halted?

It seems to be done, I'm assuming, since #429 was merged into master. I'm guessing the issue just didn't get updated.

**Comment by vinicius507** [comment]
> > The Slash Commands branch development was halted?
> 
> It seems to be done, I'm assuming, since #429 was merged into master. I'm guessing the issue just didn't get updated.

Thanks!
