### ISSUE TITLE
Incorrect http response type check for UpdateGuildMemberBuilder

### ISSUE THREAD

**Issue by m-vinc** [andersfylling/disgord#378]
**Describe the bug**
When using the UpdateGuildMemberBuilder to update a member, the Discord API is returning a 200 OK (https://discord.com/developers/docs/resources/guild#modify-guild-member) but in the code there is a middleware on the rest client (https://github.com/andersfylling/disgord/blob/develop/member.go#L85) which check if the response type is a 204 No content, so we're received an untyped error while the operation is sucessfully made ! 

**Desktop (please complete the following information):**
 - Golang version: 1.15.7
 - Using Go modules? yes
 - Disgord version? [e.g. v0.15]
 - Connected to the gateway before using REST methods? yes

**Comment by andersfylling** [comment]
nice catch, I'll update these to do a range check so it's a little more flexible.

**Comment by andersfylling** [comment]
fixed here: https://github.com/andersfylling/disgord/commit/bf4fdc59adfe84421e66b5e2d8e4103e46fcda2a

**Comment by m-vinc** [comment]
Thanks you, next time I'll try to do a PR !
