### ISSUE TITLE
Filter mention recognition dose not work if the bot has a nickname

### ISSUE THREAD

**Issue by iComputeDaily** [andersfylling/disgord#383]
**Describe the bug**
The msgFilter.ContainsBotMention function calls [std.mentionString](https://github.com/andersfylling/disgord/blob/c8dbb2f250923162f613ff0fa35c5e134274ca24/std/utils.go#L77) to get the string that the message will have if it contains the mention. However discord uses a different mention syntax if the user mentioned has a nickname. (`<@user_id>` is for without nickname, and `<@!user_id>` for with nickname.)

**Expected behavior**
That msgFilter.ContainsBotMention should detect mentions of the bot regardless of it's nickname.

**Desktop (please complete the following information):**
 - Golang version: 1.14
 - Using Go modules? yes
 - Disgord version? v0.26.8
 - Connected to the gateway before using REST methods? yes

**Additional context**
Why would discord do this? It just makes no sense to me.

**Comment by andersfylling** [comment]
Nice catch!

**Comment by iComputeDaily** [comment]
Thanks! However this only fixes it for HasBotMentionPrefix, not for ContainsBotMention, could you get that one aswell?

**Comment by andersfylling** [comment]
there we go, I'll make a release soon.
