### ISSUE TITLE
An equivalent to discordgo's ChannelVoiceJoinManual

### ISSUE THREAD

**Issue by lukasl-dev** [andersfylling/disgord#384]
**Is your feature request related to a problem? Please describe.**
I would like to use a third party voice solution called [Lavalink](https://github.com/Frederikam/Lavalink/), but this is not possible without this implementation.

**Describe the solution you'd like**
[This discordgo issue](https://github.com/bwmarrin/discordgo/issues/577) already explains it quite well.
Long story short: I want a method that performs the OP4 voice handshake and intercepts the `VOICE_SERVER_UPDATE` event to enable third party voice solutions

**Describe alternatives you've considered - optional**
[Discordgo](https://github.com/bwmarrin/discordgo) has already implemented this method. See [issue](https://github.com/bwmarrin/discordgo/issues/577).

**Comment by DasPoet** [comment]
Great idea, would love to see this as well.

**Comment by andersfylling** [comment]
Yo, I added a commit for this. Can you check if this works for you?

`Client.Guild(..).VoiceChannel(..).JoinManual(..)`

**Comment by andersfylling** [comment]
There are no tests for this, so i would consider this experimental.

**Comment by lukasl-dev** [comment]
It works, thank you :)
