### ISSUE TITLE
False Positive Error on Modifying User

### ISSUE THREAD

**Issue by suhaibmalik** [andersfylling/disgord#388]
When making changes to the user (e.g. SetRole with the Guild Member Builder) the server responds with a `200 Status OK`. Disgord currently assumes any non-empty response is an error.

**Ref:** https://github.com/andersfylling/disgord/blob/bf4fdc59adfe84421e66b5e2d8e4103e46fcda2a/member.go#L85-L90

**Example:**
```golang
err := client.Guild(gid).Member(mid).UpdateBuilder().SetRoles(roles).Execute()
if err != nil {
	fmt.Println(err)
}
```
```bash
$
resp.StatusCode = 200
string(body) = {"roles": ["xxx", "xxx"], "nick": null, "premium_since": null, "joined_at": "xxx", "is_pending": false, "pending": false, "user": {"id": "xxxx", "username": "xxxx", "avatar": "xxxx", "discriminator": "xxx", "public_flags": 0}, "mute": false, "deaf": false}

could not change attributes of member. Does the member exist, and do you have permissions?
```

**Comment by andersfylling** [comment]
Very nice catch! I think all of these could just be replaced with a 2xx range check.

**Comment by suhaibmalik** [comment]
Trying to help resolve the tests from 29f92780985a70ddce0c5851e3fce1fb2da6da2d. However, I'm not able to reproduce the errors on [my fork](https://github.com/suhaibmalik/disgord). Could this be a race condition?

Looking to help if I can. Lmk.

**Comment by andersfylling** [comment]
That sounds like the most likely issue. My linux system is broken
currently, but hopefully ill get back into fixing this.

**Comment by andersfylling** [comment]
The cache itself has some race flaws. But they arent triggered since the
cache is only updated from one goroutine, instead of one per websocket
shard.
