### ISSUE TITLE
Add support for crossposting messages

### ISSUE THREAD

**Issue by akireee** [andersfylling/disgord#389]
**Is your feature request related to a problem? Please describe.**
I'm working on a Twitch notification system for my bot that uses disgord to send out messages to channels when a Twitch user starts streaming.

I'd like to implement a feature where the bot automatically crossposts a notification message inside [announcement channels](https://support.discord.com/hc/en-us/articles/360032008192), but there doesn't seem to be a way to do this with disgord.

**Describe the solution you'd like**
A function on `Message` objects that allows you to crosspost them.

Something like this:
```go
msg, err := client.SendMsg(channelID, messageContents)
if err != nil ...

crosspostedMsg, err := msg.Crosspost()
if err != nil ...
```

**Describe alternatives you've considered - optional**
Make an HTTP request via `net/http` and POST to the crosspost endpoint manually. However, this doesn't handle ratelimiting or update the cache.

**Additional context - optional**
https://discord.com/developers/docs/resources/channel#crosspost-message

**Comment by andersfylling** [comment]
Let me know if there are any issues with this commit. From what I can tell it seems to be alright.

**Comment by akireee** [comment]
LGTM! Thanks for implementing it so quickly.
