### ISSUE TITLE
Easy way to play audio through Voice

### ISSUE THREAD

**Issue by ThallesP** [andersfylling/disgord#392]
**Is your feature request related to a problem? Please describe.**
There isn't any easy way to play audio (not in the docs), this feature will be more easily for new users of the library.

**Describe the solution you'd like**
A function in `VoiceConnection` to play audio.
For example `PlayFile("./testsound.mp3", VoiceConnection or guildID)`
And, if possible `pause(VoiceConnection or guildID)` and `resume(VoiceConnection or guildID)`

**Describe alternatives you've considered - optional**
I'm planning to do this feature with this library https://github.com/jonas747/dca which requires FFmpeg, it seems to work great, If you have any other way let me know.
I will try to implement this feature in a pull request If you approve.

**Comment by post04** [comment]
Why just mp3? I feel like `PlayFile` shouldn't be limited to just mp3's based on the name. Maybe if you only want to play mp3's the func name should be `PlayMP3`?

**Comment by ThallesP** [comment]
> Why just mp3? I feel like `PlayFile` shouldn't be limited to just mp3's based on the name. Maybe if you only want to play mp3's the func name should be `PlayMP3`? I only say that because mp4's as well as sound that can be played, so do plenty more of file types.

I'm planning to do that in the future, I'll see If the library that I'll use will support other file types or maybe I can convert it to MP3 and then pipe it to the library.

**Comment by ThallesP** [comment]
Just updated the title to not exclusive limit the audio to .mp3 format

**Comment by andersfylling** [comment]
I think that it is better to recommend a library for dca convertion in the
documentation instead of including one in disgord. Less to maintain, and
users only have to do call another function which sounds like a win to me.

There is ofc other concerns such as bugs for specific versions, which audio
formats should then be supported and on it goes.

**Comment by ThallesP** [comment]
I was thinking of having an own implemention of dca in Disgord and include
the PlayFile with that implemention but is unnecessary and complicated to
do.

I'll agree with Anders maybe can be recommend the library that I mentioned
or the bwmarrin dca implemention.

The library that I mentioned use discordgo as a dependency which seems
unnecessary to download whole library to only convert to dca.

**Comment by andersfylling** [comment]
I'm closing this for now. Feel free to create a PR for recommending dca projects.
