### ISSUE TITLE
Bot hangs after channel update

### ISSUE THREAD

**Issue by kanielc** [andersfylling/disgord#396]
**Describe the bug**
After calling channel update, bot is no longer responsive to any commands.
Executed method looks like:
```go
func (sm slowmode) Exec(s disgord.Session, data *disgord.MessageCreate) {
	msg := data.Message

	mentionedChannel, _ := 123456789
	amount := 15
	reason := "just a reason"

	_, err := s.Channel(disgord.Snowflake(mentionedChannel)).UpdateBuilder().SetRateLimitPerUser(uint(amount)).Execute()

	if err != nil {
		log.Println(err)
	}

	msg.Reply(noCtx, s, fmt.Sprintf("Set the slowmode to **%d** in the channel **<#%d>** with reason **%s**", amount, mentionedChannel, reason))
}
```

Handler looks like
```go
// handleMsg is a basic command handler
func handleMsg(s disgord.Session, data *disgord.MessageCreate) {
	msg := data.Message

	var cmdStr string
	spaceLoc := strings.Index(msg.Content, " ")
	if spaceLoc == -1 {
		cmdStr = msg.Content
	} else {
		cmdStr = msg.Content[:spaceLoc]
	}

	cmd, ok := commands.Commands[cmdStr]

	// if command not found, just return
	if !ok {
		return
	}

	cmd.Exec(s, data)
}
```

**Expected behavior**
Follow up commands should invoke the `handleMsg function`

**Error messages**
No errors are thrown

**Desktop (please complete the following information):**
 - Golang version: 1.16.3
 - Using Go modules? yes
 - Disgord version? 0.26.10
 - Connected to the gateway before using REST methods? yes

**Additional context**

Took images of the call stack with debugger and noticed a network connection thread seemed to still be active.
Everything is fine after the first image, but the second one is where it hangs.
![afterping](https://user-images.githubusercontent.com/1334074/119913467-fb90c580-bf2b-11eb-9fa9-53eeeec4bbaa.PNG)
![afterslow](https://user-images.githubusercontent.com/1334074/119913472-ffbce300-bf2b-11eb-8aae-7024f5b88d02.PNG)

**Comment by kanielc** [comment]
This seems to be the place where things go wrong.

![image](https://user-images.githubusercontent.com/1334074/120001178-8364e700-bfa1-11eb-927f-ac9d7f0629be.png)

**Comment by andersfylling** [comment]
So that fixes one potential deadlock, but i dont think that is the actual issue

**Comment by andersfylling** [comment]
Yeah apparently I lock the same mutex twice. Once in updateChannel and once before calling it in a special branch: https://github.com/andersfylling/disgord/blob/develop/cache.go#L174

**Comment by andersfylling** [comment]
fix is not yet released. but u can checkout the latest commit and give it a try

**Comment by kanielc** [comment]
It works, thanks!
