### ISSUE TITLE
Stickers not populated in incoming Message objects

### ISSUE THREAD

**Issue by kittcodes** [andersfylling/disgord#417]
**Describe the bug**
While we do have the data structures in place for Sticker objects and their relationship to Messages, Stickers aren't populating in incoming messages

**Expected behavior**
We should be able to access Stickers that are sent in a message

**Desktop (please complete the following information):**
 - Golang version: v1.16.x
 - Using Go modules? yes
 - Disgord version? v0.27.3
 - Connected to the gateway before using REST methods? yes

**Additional context**
Just opening an issue to track for future PRs

**Comment by andersfylling** [comment]
Seems Stickers are deprecated in favour of StickerItems. Update the message object in v0.28.1
