### ISSUE TITLE
No SetFlags method for Message Update Builder

### ISSUE THREAD

**Issue by ImVexed** [andersfylling/disgord#445]
**Describe the bug**
There is no SetFlags method for Message Update Builder

**Expected behavior**
There to be a SetFlags method for Message Update Builder

**Error messages**
N/A

**Desktop (please complete the following information):**
 - Golang version: 1.17.1
 - Using Go modules? yes
 - Disgord version? v0.29.0
 - Connected to the gateway before using REST methods? yes

**Additional context**
Only reference I can find to this method is in the proposed change to update builder, but it's been a few months and I was curious if there were any plans to implement before the merge of that branch. https://github.com/andersfylling/disgord/pull/420

**Comment by andersfylling** [comment]
Yes, I'm merging this tonight. I've been busy for too long and so I apologize for the slow reply.

**Comment by andersfylling** [comment]
Merged. Available under `Client.Channel(..).Message(..).Update(..)`
