### ISSUE TITLE
No way to disconnect member from channel

### ISSUE THREAD

**Issue by ImVexed** [andersfylling/disgord#446]
**Describe the bug**
UpdateGuildMemberBuilder rejects a channel ID of 0.

**Expected behavior**
Some way of passing a null value to SetChannelID to signify that the member should be disconnected (https://discord.com/developers/docs/resources/guild#modify-guild-member)

> If the channel_id is set to null, this will force the target user to be disconnected from voice.

**Desktop (please complete the following information):**
-Golang version: 1.17.1
-Using Go modules? yes
-Disgord version? v0.29.0
-Connected to the gateway before using REST methods? yes

**Comment by andersfylling** [comment]
The API seems to be a bit messy regarding voice.

Does `client.Guild(..).KickVoiceParticipant(..)` work for you?

**Comment by ImVexed** [comment]
I think `DisconnectVoiceParticipant` would probably make the most sense, discord seems to only use `Kick` to refer to removing a member from a guild. 

Either way, anything works fine!

**Comment by andersfylling** [comment]
Oh, fair. I guess the `Kick` prefix can be a bit scary.
