### ISSUE TITLE
VoiceState missing fields

### ISSUE THREAD

**Issue by ImVexed** [andersfylling/disgord#464]
**Describe the bug**
VoiceState is missing 3 new fields since it was last reviewed.

**Expected behavior**
According to https://discord.com/developers/docs/resources/voice#voice-state-object it's missing:  
`self_stream`    
`self_video`  
`request_to_speak_timestamp`  

**Desktop (please complete the following information):**
 - Golang version: 1.18
 - Disgord version? 0.31

**Comment by andersfylling** [comment]
https://github.com/andersfylling/disgord/commit/710caafba202c167b301ac974e227d0711892c02
