### ISSUE TITLE
Can`t get user input from interaction event: missing fields

### ISSUE THREAD

**Issue by SergeyGulidov** [andersfylling/disgord#465]
**Describe the bug**
Can`t get user input from interaction event when user selects some option from message with select component. 
![image](https://user-images.githubusercontent.com/1598127/147920064-4801338e-06db-41f8-960b-cfa71ae08ad8.png)

**Expected behavior**
There need to be: ***disgord.InteractionCreate.Data.Values**  array with user selected values
Doc: https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-menu-interaction

And there are not enough fields in the component for everything work great: 
**Placeholder  string, 
MinValues    integer,  
MaxValues   integer,** 

![image](https://user-images.githubusercontent.com/1598127/147920562-c305373a-091a-40ae-b22b-543c74fa1408.png)

 - Golang version: v1.17
 - Using Go modules? yes
 - Disgord version: v0.31.1
 - Connected to the gateway before using REST methods? yes

**Comment by andersfylling** [comment]
I'll fix this up after work today, thanks for the report :+1:

**Comment by andersfylling** [comment]
Hi, this should be fixed here: https://github.com/andersfylling/disgord/releases/tag/v0.32.0

please let me know if you find new issues

**Comment by SergeyGulidov** [comment]
Thanks - very nice, but... 
![image](https://user-images.githubusercontent.com/1598127/148027158-fda9cae2-7ef0-436c-a937-5b894812e46c.png)

Error occurred when user choose one option from select. When event client.Gateway().InteractionCreate() starts. 
v0.32.0

Oh, those selects ʕ•ᴥ•ʔ

**Comment by andersfylling** [comment]
Ah, it seems it's time to improve my integration tests :sweat_smile:

**Comment by andersfylling** [comment]
@SergeyGulidov I updated the field to be string. Sorry about the annoyance.
