### ISSUE TITLE
How to get users in scheduled event?

### ISSUE THREAD

**Issue by Aldiwildan77** [andersfylling/disgord#467]
The [Discord API](https://discord.com/developers/docs/resources/guild-scheduled-event#get-guild-scheduled-event-users) supports getting users who subscribed to the scheduled event, but I can't find this method in disgord. 

So can I use another approach or this method is currently not available yet in disgord?

**Comment by andersfylling** [comment]
I believe disgord lacks the implementation. I haven't started on implementing this. I'm currently occupied by work and won't have eyes on this for some time.

**Comment by Aldiwildan77** [comment]
oh, I see, I'll try to make it because i need this new feature for my custom bot

**Comment by Aldiwildan77** [comment]
maybe, this issue will still open till the pull request is created
