### ISSUE TITLE
[Discussion] Bot interface

### ISSUE THREAD

**Issue by andersfylling** [andersfylling/disgord#63]
There was shown interest for having a command register for bots.

Because of this I suggest creating a Bot interface. But not to mix any of this into the existing disgord.Session interface. Instead the Bot interface will hold a disgord.Session instance and enforce some bot behavior rules as written later in this article.

disgord.NewBotInstance:
An exported function for constructing the Bot called `NewBotInstance` and will handle the following:
 - default disgord.Config setup if not provided in disgord.BotConfig.SessionConfig.
 - Returns a disgord.Bot interface and an error

disgord.Bot
 - RegisterCmd
   Register a command. It takes the argument of a *BotCommand struct which holds the handler, command name, description, etc.
 - SetState
   Makes it easy to quickly change bot behavior. An example would be the state "silence"; the bot do not send out any messages, and is currently viewed as in-active. Users should be able to register command handlers for specific states (to keep code cleaner), and create their own custom states. Another state could be "normal" which implicits the default behavior, or debug to start debugging (without recompiling/restarting). This does also require the state to be stored persistently as the bot might have to restart, be it suddenly or planned.
 - RegisterService
   Long-running task that should not be handled in a command. It will have access to the disgord.Session interface.
 - On (wrapper for disgord.Session.On)
   For listening to events, when a command does just not qualify.
 - Start
   Starts the bot instance. Always connects to the socket API (which is required to make the entire REST api functional)
 - Stop
   Stops the bot instance (graceful)
 - Session
   Which simply returns the disgord.Session interface (the actual instance used by the bot)

disgord.BotConfig:
 - SessionConfig *disgord.Config
 - Name string
   Name of the bot. If not set, it will default to the Discord name.
 - SourceURL string
   A URL for contributors. GitHub, Bitbucket, whatever you feel like.
 - Description
   explanation what the bot does
 - CommandPrefix string
   A prefix applied to all commands
 - State
   default: normal. The "bot mood" or core behaviour as explained above in the Bot interface.
 - Token string (required)
   Discord Token for interacting with Discord
 - Commands []*disgord.BotCommand
   Commands the bot should support. Alternatively, they can be registered live.
 - Services []*disgord.BotService
   For long-running tasks that should run all the time or until is terminated by the bot application or another process. These must take a context.Context as their first parameter to support cancelation. Alternatively, they can be registered live.
 - EventHandlers map[string]interface{}
   When a BotCommand is restricting the behavior of the bot, a custom event listener can be used instead to give more freedom to the developer. Alternatively, they can be registered live.

disgord.BotCommand:
 - Trigger string (required)
   Also the name of the command. eg. !ping. Here "ping" is the Trigger for the command.
 - ShortDesc string (required)
   A short description for the command.
 - LongDesc string 
   A in depth description of what the command does. Usually with examples. If not set, it defaults to ShortDesc.
 - Handler *BotCommandHandler
   Default handler for the command. This is run whenever a handler can not be found for a given state. If no handler is registered and a handler is not found in the StateHandlers, nothing is executed. Exception is logged.
 - StateHandlers map[string]*BotCommandHandler
   Allows for binding different handlers to specific bot states. 
 - Flags interface{}
   Allow terminal type args. go-args package will be used for parsing these. used to generate a *arg.Parser. eg. `!chessgame --start --name="something" --player1=@user1 --player2=@user2`
 - Permissions
   Set the discord permissions required for this command. It's just a step to improve performance.
 - BotFriendly bool
   Set to true if this command can be trigger by other bots. Default behavior is false.

disgord.BotService:
 - Name (required)
 - ShortDesc (required)
   Short description of the behavior/goal.
 - LongDesc
   In-depth description. defaults to ShortDesc on nil/empty.
 - Func *disgord.BotServiceFunc
   the function to be run
 - Data map[interface{}]interface{}
   Allows for accessible storage for the services. This data can also be accessed by commands.

Rules:
 - BotCommand will not be triggered by itself.
 - BotCommand can be triggered by another bot, but this must be specified in *disgord.BotCommand. There must be a variable to easily check if a command was triggered by a bot as well.

Please discuss the matter. All comments are welcome. If you only want to express thoughts such as "I like this" or "I dislike this" without any reason. Use emoji's / reactions such as thumbs up and thumbs down.

**Comment by andersfylling** [comment]
See middleware proposal #91

**Comment by andersfylling** [comment]
Current iteration aims to add the command struct and a way to register it. Will use the session interface for now.

**Comment by andersfylling** [comment]
See progress here: https://github.com/andersfylling/disgord/pull/234

This PR aims to implement the command struct and a way to register commands. Some features might be missing, some might be added, this is because the current issue draft is a bit outdated and the requirements are reviewed/reconsidered as the PR develops.

**Comment by midona-rhel** [comment]
May I suggest that the disgord.BotCommand interface specifies a `Nsfw(): bool` function as to make sure that some commands may adhere to the nsfw policy discord implements on their channels

**Comment by midona-rhel** [comment]
Also in addition, I like the idea of Commands, State and Services being toggle-able per guild, this would allow a developer to add the functionality for an administrator to quickly mute the bot, stop a service, or disable a command for that guild. This should probably not be implemented in the disgord library per say but rather open up the ability to do so via `bot.DisableCommand(commandName, guild)` for example (sounds very clunky however with the state dependant commands so this is probably not an optimal solution).

**Comment by andersfylling** [comment]
I'm going to let other libs handle this. So I can focus on the core logic
