### ISSUE TITLE
Low test coverage in DisGord

### ISSUE THREAD

**Issue by MarkusAJacobsen** [andersfylling/disgord#88]
A higher test coverage should be achieved as it to some extent ensures others that such considerations have been made, and that functionality have been quality checked beyond code review.

**Comment by andersfylling** [comment]
I'm closing this when DisGord reaches 30% to 40% test coverage, due to it being too broad and difficult to tackle. After that, test coverage should regard per feature as not everything can nor should be unit tested.

**Comment by andersfylling** [comment]
Currently the test coverage from the integration tests aren't included in the score. Which sucks.

I'm closing this as it is a bit broad while disgord being still in development - non stable API.
