### ISSUE TITLE
Missing Voice support

### ISSUE THREAD

**Issue by andersfylling** [andersfylling/disgord#92]

**Comment by ikkerens** [comment]
Voice sending was implemented in the voice branch, voice receive is currently pending Minn's plea in https://github.com/discordapp/discord-api-docs/issues/808#issuecomment-457962359

Tbh - I'd rather avoid implementing voice receive until we actually get documentation on it (right now there is *none*)

**Comment by andersfylling** [comment]
Yeah, you got my full support on ignoring receive until it get's stable/documented.
